Added new pasring of argv to db-select-mysql

diff --git a/install/db-select-mysql b/install/db-select-mysql
--- a/install/db-select-mysql
+++ b/install/db-select-mysql
@@ -1,7 +1,30 @@
 #!/bin/bash
 
-(>&2 "This script is deprecated. Use mysqlgovernor.py --mysql-version instead")
 
-if [ "$1" == "-m" ] || [ "$1" == "--mysql-version" ]; then
-    /usr/share/lve/dbgovernor/mysqlgovernor.py --mysql-version $2;
+
+OPTS=`getopt -o hm: --long help,mysql-version: -n 'parse-options' -- "$@"`
+
+if [ $? != 0 ] ; then echo "Failed parsing options." >&2 ; exit 1 ; fi
+
+echo "This script is deprecated. Use -- mysqlgovernor.py $OPTS instead"
+
+eval set -- "$OPTS"
+
+HELP=""
+MYSQL_SET_VER=""
+
+while true; do
+  case "$1" in
+    -h | --help )    HELP="y"; shift ;;
+    -m | --mysql-version ) MYSQL_SET_VER="$2"; shift; shift ;;
+    -- ) shift; break ;;
+    * ) break ;;
+  esac
+done
+
+if [ -n "$MYSQL_SET_VER" ]; then
+    /usr/share/lve/dbgovernor/mysqlgovernor.py --mysql-version $MYSQL_SET_VER;
+    exit 0
 fi;
+
+/usr/share/lve/dbgovernor/mysqlgovernor.py --help;
